import datetime
import os


class Config(object):
    DEBUG = False
    TESTING = False
    QRCODES_DIR = "qrcodes"


class ProductionConfig(Config):
    # DATABASE_URI = 'mysql://user@localhost/foo'
    # DATABASE_URI = 'mysql://user@localhost/foo'
    # DATABASE_URI = 'sqlite:///:memory:'
    SECRET_KEY = <PRODUCTION_SECRET_KEY>
    SALT = <PRODUCTION_BYTES_LITERAL_SALT>
    DB_USER = <PRODUCTION_DATABASE_USERNAME>
    DB_NAME = <PRODUCTION_DATABASE_NAME>
    DB_HOST = <PRODUCTION_DATABASE_HOST_URI>
    DB_PORT = <PRODUCTION_DATABASE_PORT>
    DB_PASSWORD = <PRODUCTION_DATABASE_PASSWORD>
    CENTER_SERVICES_USER = <PRODUCTION_CENTER_SERVICES_USERNAME>
    CENTER_SERVICES_ROLE = <PRODUCTION_CENTER_SERVICES_ROLE>  # e.g.: "cs_user"
    SEND_MSG_USER = <PRODUCTION_SEND_MSG_USERNAME >
    SEND_MSG_ROLE = <PRODUCTION_SEND_MSG_ROLE>  # e.g. : "sm_user"
    PASSCODE_MAX_USES = 10
    # JWT_EXPIRATION_DELTA
    JWT_ACCESS_TOKEN_EXPIRES = datetime.timedelta(minutes=30)
    # JWT_HEADER_TYPE = ""
    SMS_SERVER = <PRODUCTION_SMS_SERVER_URI>
    SMS_API_KEY = <PRODUCTION_SMS_API_KEY>


class DevelopmentConfig(Config):
    SECRET_KEY = <DEVELOPMENT_SECRET_KEY>
    SALT = <DEVELOPMENT_BYTES_LITERAL_SALT>
    DB_USER = <DEVELOPMENT_DATABASE_USERNAME>
    DB_NAME = <DEVELOPMENT_DATABASE_NAME>
    DB_HOST = <DEVELOPMENT_DATABASE_HOST_URI>
    DB_PORT = <DEVELOPMENT_DATABASE_PORT>
    DB_PASSWORD = <DEVELOPMENT_DATABASE_PASSWORD>
    CENTER_SERVICES_USER = <DEVELOPMENT_CENTER_SERVICES_USERNAME>
    CENTER_SERVICES_ROLE = <DEVELOPMENT_CENTER_SERVICES_ROLE>  # e.g.: "cs_user"
    SEND_MSG_USER = <DEVELOPMENT_SEND_MSG_USERNAME >
    SEND_MSG_ROLE = <DEVELOPMENT_SEND_MSG_ROLE>  # e.g. : "sm_user"
    PASSCODE_MAX_USES = 30
    # JWT_EXPIRATION_DELTA
    JWT_ACCESS_TOKEN_EXPIRES = datetime.timedelta(minutes=30)
    # JWT_HEADER_TYPE = ""
    SMS_SERVER = <DEVELOPMENT_SMS_SERVER_URI>
    SMS_API_KEY = <DEVELOPMENT_SMS_API_KEY>


class TestingConfig(Config):
    TESTING = True
